### ISSUE TITLE
http://izpm.wonyoung.kr/ seems not loadiing

### ISSUE THREAD

**Issue by lnn823** [mdsnins/IZPM-Backup#10]
Failed to load http://izpm.wonyoung.kr/, both with and without proxy.

**Comment by mdsnins** [comment]
I confirmed it.

I just checked it the traffic and resource usage is rapidly increased since this midnight, and I missed it. Because the server is running on my personal tiny AWS instance, it seems likes it couldn't process the load properly. I'm going to upgrade an instance in few minutes and restart the service. When it's done, I'll make an another answer here.

Sorry for inconvenience.

**Comment by mdsnins** [comment]
Okay, I just upgraded it to larger instance, and it seems working now.
If the problem occurs again, please feel free to leave an issue.

Thanks!
